# Generated by Django 6.1.1 on 2026-10-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="value",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Баллы / Оценка"
            ),
        ),
    ]
